__title__ = 'Astro EDMS'
__version__ = '4.11.3'
__build__ = 0x041103
__build_string__ = 'v4.11.3_Mon Apr 27 20:15:00 2026 -0400'
__django_version__ = '5.2'
__author__ = 'Henry Mate'
__author_email__ = 'matehenrie@gmail.com'
__description__ = 'Free Open Source Electronic Document Management System'
__license__ = 'GPL 2.0'
__copyright_short__ = '2026 Astro'
__copyright__ = '{} {}'.format('Copyright', __copyright_short__)
__website__ = 'https://www.astro-edms.com'
